---
AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a stack containing an IAM role used to grant
  Cloud Secure monitoring access to AWS infrastructures.

Parameters:
  CloudPassageAwsAccount:
    Type: String
    Description: Enter the CloudPassage AWS account number shown on your Cloud Secure Integrations page.
  CloudSecureExternalId:
    Type: String
    Description: Enter the unique externID from the Halo Cloud Secure Integrations page or generate your own external uuid.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cloud Secure AWS Account ID and External ID"
        Parameters:
          - CloudPassageAwsAccount
          - CloudSecureExternalId
    ParameterLabels:
      CloudPassageAwsAccount:
        default: CloudPassage AWS ID
      CloudSecureExternalId:
        default: Cloud Secure External ID



Resources:
  HaloCloudSecureCrossAccountPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "HaloCloudSecurePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
          - acm:DescribeCertificate
          - acm:ListCertificates
          - application-autoscaling:Describe*
          - autoscaling:Describe*
          - batch:DescribeComputeEnvironments
          - batch:DescribeJobDefinitions
          - clouddirectory:ListDirectories
          - cloudformation:DescribeStack*
          - cloudformation:GetTemplate
          - cloudformation:ListStack*
          - cloudformation:GetStackPolicy
          - cloudfront:Get*
          - cloudfront:List*
          - cloudhsm:ListHapgs
          - cloudhsm:ListHsms
          - cloudhsm:ListLunaClients
          - cloudsearch:DescribeDomains
          - cloudsearch:DescribeServiceAccessPolicies
          - cloudtrail:DescribeTrails
          - cloudtrail:GetTrailStatus
          - cloudtrail:ListTags
          - cloudwatch:Describe*
          - codebuild:ListProjects
          - codecommit:BatchGetRepositories
          - codecommit:GetBranch
          - codecommit:GetObjectIdentifier
          - codecommit:GetRepository
          - codecommit:List*
          - codedeploy:Batch*
          - codedeploy:Get*
          - codedeploy:List*
          - codepipeline:ListPipelines
          - cognito-identity:ListIdentityPools
          - cognito-idp:ListUserPools
          - config:Deliver*
          - config:Describe*
          - config:Get*
          - datapipeline:DescribeObjects
          - datapipeline:DescribePipelines
          - datapipeline:EvaluateExpression
          - datapipeline:GetPipelineDefinition
          - datapipeline:ListPipelines
          - datapipeline:QueryObjects
          - datapipeline:ValidatePipelineDefinition
          - directconnect:Describe*
          - ds:DescribeDirectories
          - dynamodb:ListStreams
          - dynamodb:ListTables
          - ec2:Describe*
          - ecr:DescribeRepositories
          - ecr:GetRepositoryPolicy
          - ecs:Describe*
          - ecs:List*
          - elasticache:Describe*
          - elasticbeanstalk:Describe*
          - elasticfilesystem:DescribeFileSystems
          - elasticloadbalancing:Describe*
          - elasticmapreduce:DescribeJobFlows
          - elasticmapreduce:ListClusters
          - elasticmapreduce:ListInstances
          - es:Describe*
          - es:ListDomainNames
          - events:DescribeEventBus
          - events:ListRules
          - firehose:Describe*
          - firehose:List*
          - gamelift:ListBuilds
          - gamelift:ListFleets
          - glacier:DescribeVault
          - glacier:GetVaultAccessPolicy
          - glacier:ListVaults
          - iam:GenerateCredentialReport
          - iam:Get*
          - iam:List*
          - iot:ListThings
          - kinesis:ListStreams
          - kinesisanalytics:ListApplications
          - kms:Describe*
          - kms:Get*
          - kms:List*
          - lambda:GetAccountSettings
          - lambda:GetPolicy
          - lambda:ListFunctions
          - logs:DescribeDestinations
          - logs:DescribeLogGroups
          - logs:DescribeMetricFilters
          - logs:DescribeResourcePolicies
          - machinelearning:DescribeMLModels
          - mediastore:GetContainerPolicy
          - mediastore:ListContainers
          - opsworks-cm:DescribeServers
          - rds:Describe*
          - rds:DownloadDBLogFilePortion
          - rds:ListTagsForResource
          - redshift:Describe*
          - route53:Get*
          - route53:List*
          - route53domains:GetDomainDetail
          - route53domains:GetOperationDetail
          - route53domains:ListDomains
          - route53domains:ListOperations
          - route53domains:ListTagsForDomain
          - s3:GetAccelerateConfiguration
          - s3:GetAnalyticsConfiguration
          - s3:GetBucket*
          - s3:GetEncryptionConfiguration
          - s3:GetInventoryConfiguration
          - s3:GetLifecycleConfiguration
          - s3:GetMetricsConfiguration
          - s3:GetObjectAcl
          - s3:GetObjectVersionAcl
          - s3:GetReplicationConfiguration
          - s3:ListAllMyBuckets
          - sdb:DomainMetadata
          - sdb:ListDomains
          - serverlessrepo:GetApplicationPolicy
          - serverlessrepo:ListApplications
          - ses:GetIdentityDkimAttributes
          - ses:GetIdentityVerificationAttributes
          - ses:ListIdentities
          - snowball:ListClusters
          - snowball:ListJobs
          - sns:GetTopicAttributes
          - sns:ListSubscriptionsByTopic
          - sns:ListTopics
          - sqs:GetQueueAttributes
          - sqs:ListQueues
          - ssm:DescribeDocumentPermission
          - ssm:ListDocuments
          - states:ListStateMachines
          - storagegateway:DescribeBandwidthRateLimit
          - storagegateway:DescribeCache
          - storagegateway:DescribeCachediSCSIVolumes
          - storagegateway:DescribeGatewayInformation
          - storagegateway:DescribeMaintenanceStartTime
          - storagegateway:DescribeNFSFileShares
          - storagegateway:DescribeSnapshotSchedule
          - storagegateway:DescribeStorediSCSIVolumes
          - storagegateway:DescribeTapeArchives
          - storagegateway:DescribeTapeRecoveryPoints
          - storagegateway:DescribeTapes
          - storagegateway:DescribeUploadBuffer
          - storagegateway:DescribeVTLDevices
          - storagegateway:DescribeWorkingStorage
          - storagegateway:List*
          - tag:GetResources
          - tag:GetTagKeys
          - trustedadvisor:Describe*
          - waf:ListWebACLs
          - waf-regional:ListWebACLs
          - workspaces:Describe*
          - lambda:ListFunctions
          - dynamodb:ListTables
          - lambda:ListVersionsByFunction
          - dynamodb:ListBackups
          - dynamodb:ListTagsOfResource
          - lambda:GetAccountSettings
          - sqs:ListQueueTags
          - ecr:ListImages
          - dynamodb:ListGlobalTables
          - lambda:ListTags
          - ecr:DescribeImages
          - ecr:DescribeRepositories
          - apigateway:GET
          - lambda:GetPolicy
          Effect: Allow
          Resource: "*"


  HaloCloudSecureCrossAccountRole:
    DependsOn: HaloCloudSecureCrossAccountPolicy
    Type: AWS::IAM::Role
    Properties:
      RoleName: "HaloCloudSecureCrossAccountRole"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub arn:aws:iam::${CloudPassageAwsAccount}:root
          Action: "sts:AssumeRole"
          Condition:
            StringEquals:
              sts:ExternalId: !Sub ${CloudSecureExternalId}
      ManagedPolicyArns:
        - !Ref HaloCloudSecureCrossAccountPolicy
